spring:
  flyway:
    locations: classpath:/db/migration # migration ???? ???? directory
    sql-migration-suffixes: ddl        # ?? ???
    baseline-on-migrate: true          # flyway_schema_history ???? ???? ???? ??
    baseline-version: 0